name: yutaa_customer_app
description: Customer application for Yutaa Service Marketplace.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Local Shared Package
  yutaa_shared:
    path: ../shared

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Routing
  go_router: ^14.2.3

  # UI & Components
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10
  intl_phone_field: ^3.2.0
  pinput: ^5.0.0
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.2

  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4

  # Maps
  google_maps_flutter: ^2.10.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13

  riverpod_generator: ^2.4.2
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/Logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
